### ISSUE TITLE
New build and error when trying to use it.

### ISSUE THREAD

**Issue by Altalus** [h1pp0/FFACETools_ffevo.net#4]
Working on the Gambest project (found here on GitHub) I rebuild FFACTTools from the latest commit, and loading the DLL in Gambest. When I try the following (VB.NET, the language used by the original author of Gambest) it gives an error:

```VB.NET
Dim instance As New FFACE(ffxi.Id)
```

I get this error:

```
An unhandled exception of type 'System.BadImageFormatException' occurred in FFACETools.dll

Additional information: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```

I made sure both FFACETools and Gambot are build with x86 as target. FFACETools DLL is built as release using the solution provided in your repository.

Any idea?

Thanks :)

**Comment by atom0s** [comment]
A few things come to mind to check:
 * Be sure you have the latest version of FFACE and FFACETools.
 * Be sure you are compiling your project that is making use of FFACE/FFACETools as x86. (Do not use Any CPU.)
 * Be sure you have the proper runtime installed for FFACE. It needs the 32bit version of the Visual C++ 2013 runtime. (Download here: https://www.microsoft.com/en-us/download/details.aspx?id=40784 -- Only get the 32bit version, not the 64bit version!)
 * Right-click on the FFACE.dll and FFACETools.dll and go to properties and make sure they are unblocked.

**Comment by Altalus** [comment]
Do you know where to get the latest version of FFACE? FFACETools I can compile but I cannot find the latest FFACE sonce the FFEvo.net server crash :-/

I made sure the target for both projects is x86.

I now have the error at a different location (I think it might be because I compiled the FFACETools as debug to test things out.

```C#
public FFACE (int processID)
        {
            // create our FFACE instance
            _InstanceID = CreateInstance((UInt32)processID);
```

Call stack:
```
>	FFACETools.dll!FFACETools.FFACE.FFACE(int processID) Line 115	C#
 	Gambest.exe!Gambest.Main.Main() Line 51	Basic
```

So either I am not using the right FFACE.dll (cannot find where to update it) or I am doing something very weird and stupid :P

A side note, it worked perfectly all right before May update and all the updates to the other tools... I think you might be right with your 1st point.

**Comment by Altalus** [comment]
I was able to find the latest version of FFACE from another tool's repository and it now works. Thank you for the help and sorry for the trouble!
