### ISSUE TITLE
n00b question~

### ISSUE THREAD

**Issue by Jacaut** [h1pp0/FFACETools_ffevo.net#5]
hi on a program im using i get this message
method not found: 'System.String NPCTools.Name(Int16)'.

I think the issue is with ffacetool, but i really know nothing about this kind of stuff, any idea what i can do to fix it?

**Comment by atom0s** [comment]
The application you are using needs to update to the latest FFACETools.
NPCTools.Name expects an int, not an int16.

**Comment by Jacaut** [comment]
i downloaded the one from this page, unless there is another one updated somewhere?

**Comment by atom0s** [comment]
What application are you having issues with?

**Comment by Jacaut** [comment]
ffxihelper, it hasnt been updated for a long time, but was still working until this last update

**Comment by atom0s** [comment]
The latest FFACETools can be downloaded here:
https://github.com/h1pp0/FFACETools_ffevo.net/blob/master/Binary/FFACETools.dll?raw=true

Be sure you are overwriting the proper file.

**Comment by Jacaut** [comment]
still gives the same message

**Comment by atom0s** [comment]
Do you have a link to download that application?

**Comment by Jacaut** [comment]
no, ive tried to find a website that has it still, is there a way i can upload it?

**Comment by atom0s** [comment]
You can use any free service such as dropbox, speedyshare, or similar.

**Comment by Jacaut** [comment]
thanks, photobucket can still mess with my mind if i try to use it @.@

http://speedy.sh/afWqb/FFXIhelper

think i did that right

**Comment by atom0s** [comment]
That file is invalid / null. You sure you uploaded the right thing?

**Comment by Jacaut** [comment]
tried to do the whole folder and i guess it didnt work, now theyre all seperate >.<
http://speedy.sh/QbStp/FFACE.dll
http://speedy.sh/yGCPZ/FFACETools.dll
http://speedy.sh/BRY65/abils.xml
http://speedy.sh/rSamx/areas.xml
http://speedy.sh/3CTfz/FFXIHelper.exe
http://speedy.sh/DYs7u/items-armor.xml
http://speedy.sh/vaJhQ/items-general.xml
http://speedy.sh/nT2Wy/items-weapons.xml
http://speedy.sh/NsewB/md5check.xml
http://speedy.sh/kJX4r/resources.xml
http://speedy.sh/t2c93/spells.xml
http://speedy.sh/Pe8AD/status.xml

**Comment by atom0s** [comment]
Looks like Speedyshare is having issues with their servers, none of the files download properly. Can you try another service instead?

**Comment by Jacaut** [comment]
lets see if i got this one right!

https://www.dropbox.com/sh/m2ctv3u0urdbw09/AACcuKymcZDozmJB_GzOFpk2a?dl=0

**Comment by atom0s** [comment]
This application enforces casting that causes issues with FFACETools. In order for it to work again the app needs to either be recompiled with proper castings, or you will need to edit it with an IL editor manually to alter the castings yourself. This is not a problem with FFACETools though.
