### ISSUE TITLE
FFACETools Chatmode/Parsing Broken?

### ISSUE THREAD

**Issue by Nexaii** [h1pp0/FFACETools_ffevo.net#6]
Hello!

Unfortunately this recent update, September 15 2015 seems to have broken something within the chatmode or parsing of FFACETools. ie; alarms no longer activate in programs like exiled.
SE adjusted the configuration of the chat windows so I imagine this might have something to do with it.

Thanks for all your time and help :)

**Comment by atom0s** [comment]
Be sure you have updated to the latest FFACE.dll
