### ISSUE TITLE
Targeting, engaging and usage of abilities

### ISSUE THREAD

**Issue by Nexaii** [h1pp0/FFACETools_ffevo.net#7]
Using the latest FFACE 4.2.0.14 which was released after the 12/9/15 update.

Cannot target/engage mobs or perform any abilities in a couple of programs that utilize ffacetools. 

Thanks for your time and help :)

**Comment by h1pp0** [comment]
ffacetools is a wrapper for fface so if there is an issue targeting it most likely is duo to the ffxi update breaking ffxi. I would wait for an update to be released and see if that fixes your issue
